#!/usr/bin/env sh

# Bangla date count starts with the rising of the sun. So date is corrected to change at 6 in the morning with GMT. If date doesn't change accordingly uncomment line 16  and comment 17.

while getopts "ed:m:y:f:h" o; do case "${o}" in
    h) printf "bncal\\n -d: Date\\n -m: Month\\n -y: Year\\n -f: Date Format\\n -e: Text Format(Bangreji)\\n -h: help\\n" && exit 1 ;;
	d) en_dt=${OPTARG} ;;
	m) en_m=${OPTARG} ;;
	y) en_y=${OPTARG} ;;
	f) dt_f=${OPTARG} ;;
	e) txt="0" ;;
	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done

# [ -z $en_dt ] && en_dt=$(date +%d | sed 's/^0//g')
[ -z $en_dt ] && en_dt=$(TZ='Europe/London' date +"%d" | sed 's/^0//g')
[ -z $en_m ] && en_m=$(date +%m | sed 's/^0//g')
[ -z $en_y ] && en_y=$(date +%Y)
[ -z $dt_f ] && dt_f="0"

lp_y=$(( $en_y % 4 ))
en_d=$(date --date=$en_y-$en_m-$en_dt +%u)
# en_d=$(date +%u)


bongabdo() {
    if [ $en_m -eq 4 ]; then
        if [ $en_dt -le 13 ]; then
        bn_y=$(( $en_y - 594 ))
    else 
        bn_y=$(( $en_y - 593 ))
        fi

    elif [ $en_m -lt 4 ]; then
        bn_y=$(( $en_y - 594 ))
    elif [ $en_m -gt 4 ]; then
        bn_y=$(( $en_y - 593 ))
    fi

    if [ $en_m -eq 4 ]; then
        if [ $en_dt -lt 14 ]; then
            bn_m=c
            bn_s=6
            bn_dt=$(( $en_dt + 14 + 3 ))
        elif [ $en_dt -ge 14 ]; then
            bn_m=1
            bn_s=1
            bn_dt=$(( $en_dt - 14 + 1 ))
        fi
    fi

    if [ $en_m -eq 5 ]; then
        if [ $en_dt -lt 15 ]; then
            bn_m=1
            bn_s=1
            bn_dt=$(( $en_dt + 15 + 2 ))
        elif [ $en_dt -ge 15 ]; then
            bn_m=2
            bn_s=1
            bn_dt=$(( $en_dt - 15 + 1 ))
        fi
    fi

    if [ $en_m -eq 6 ]; then
        if [ $en_dt -lt 15 ]; then
            bn_m=2
            bn_s=1
            bn_dt=$(( $en_dt + 15 + 2 ))
        elif [ $en_dt -ge 15 ]; then
            bn_m=3
            bn_s=2
            bn_dt=$(( $en_dt - 15 + 1 ))
        fi
    fi

    if [ $en_m -eq 7 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=3
            bn_s=2
            bn_dt=$(( $en_dt + 16 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=4
            bn_s=2
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 8 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=4
            bn_s=2
            bn_dt=$(( $en_dt + 16 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=5
            bn_s=3
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 9 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=5
            bn_s=3
            bn_dt=$(( $en_dt + 16 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=6
            bn_s=3
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 10 ]; then
        if [ $en_dt -lt 17 ]; then
            bn_m=6
            bn_s=3
            bn_dt=$(( $en_dt + 15 ))
        elif [ $en_dt -ge 17 ]; then
            bn_m=7
            bn_s=4
            bn_dt=$(( $en_dt - 17 + 1 ))
        fi
    fi

    if [ $en_m -eq 11 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=7
            bn_s=4
            bn_dt=$(( $en_dt + 14 + 1 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=8
            bn_s=4
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 12 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=8
            bn_s=4
            bn_dt=$(( $en_dt + 14 + 1 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=9
            bn_s=5
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 1 ]; then
        if [ $en_dt -lt 15 ]; then
            bn_m=9
            bn_s=5
            bn_dt=$(( $en_dt + 13 + 3 ))
        elif [ $en_dt -ge 15 ]; then
            bn_m=m
            bn_s=5
            bn_dt=$(( $en_dt - 15 + 1 ))
        fi
    fi

    if [ $en_m -eq 2 ]; then
        if [ $en_dt -lt 14 ]; then
            bn_m=m
            bn_s=5
            bn_dt=$(( $en_dt + 12 + 5 ))
        elif [ $en_dt -ge 14 ]; then
            bn_m=f
            bn_s=6
            bn_dt=$(( $en_dt - 14 + 1 ))
        fi
    fi

    if [ $en_m -eq 3 ]; then
        if [ $en_dt -lt 15 ]; then
            if [ $lp_y -ne 0 ]; then
                bn_m=f
                bn_s=6
                bn_dt=$(( $en_dt + 15 ))
            else
                bn_m=f
                bn_s=6
                bn_dt=$(( $en_dt + 15 + 1 ))
            fi
        elif [ $en_dt -ge 15 ]; then
            bn_m=c
            bn_s=6
            bn_dt=$(( $en_dt - 15 + 1 ))
        fi
    fi

    if [ -z $txt ]; then
        din=$(printf "%s" $en_d | sed 's/1/সোম/;s/2/মঙ্গল/;s/3/বুধ/;s/4/বৃহঃ/;s/5/শুক্র/;s/6/শনি/;s/7/রবি/')
        tariq=$(printf "%s" $bn_dt | sed 's/1/১/g;s/2/২/g;s/3/৩/g;s/4/৪/g;s/5/৫/g;s/6/৬/g;s/7/৭/g;s/8/৮/g;s/9/৯/g;s/0/০/g')
        mas=$(printf "%s" $bn_m | sed 's/1/বৈশাখ/;s/2/জ্যৈষ্ঠ/;s/3/আষাঢ়/;s/4/শ্রাবণ/;s/5/ভাদ্র/;s/6/আশ্বিন/;s/7/কার্তিক/;s/8/অগ্রহায়ণ/;s/9/পৌষ/;s/m/মাঘ/;s/f/ফাল্গুন/;s/c/চৈত্র/')
        son=$(printf "%s" $bn_y | sed 's/1/১/g;s/2/২/g;s/3/৩/g;s/4/৪/g;s/5/৫/g;s/6/৬/g;s/7/৭/g;s/8/৮/g;s/9/৯/g;s/0/০/g')
        hritu=$(printf "%s" $bn_s | sed 's/1/গ্রীষ্ম/;s/2/বর্ষা/;s/3/শরৎ/;s/4/হেমন্ত/;s/5/শীত/;s/6/বসন্ত/')
    else
        din=$(printf "%s" $en_d | sed 's/1/Som/;s/2/Mongol/;s/3/Budh/;s/4/Briho/;s/5/Shukro/;s/6/Shoni/;s/7/Robi/')
        tariq=$bn_dt
        mas=$(printf "%s" $bn_m | sed 's/1/Boishakh/;s/2/Jaishtha/;s/3/Aashar/;s/4/Srabon/;s/5/Vhadra/;s/6/Aashwin/;s/7/Kartik/;s/8/Aagrahayon/;s/9/Poush/;s/m/Magh/;s/f/Falgun/;s/c/Chaitra/')
        son=$bn_y
        hritu=$(printf "%s" $bn_s | sed 's/1/Grishsho/;s/2/Borsha/;s/3/Sharot/;s/4/Hemanta/;s/5/Sheet/;s/6/Bosonto/')
    fi

    if [ $dt_f -eq 1 ]; then
         printf "%s %s %s" $din $tariq $mas
    elif [ $dt_f -eq 2 ]; then
        printf "%s %s %s %s" $din $tariq $mas $son
    elif [ $dt_f -eq 3 ]; then
        printf "%s %s %s" $hritu $tariq $mas
    elif [ $dt_f -eq 4 ]; then
        printf "%s %s %s %s" $hritu $tariq $mas $son
    elif [ $dt_f -eq 5 ]; then
        printf "%s %s" "$tariq "$mas
    else
        printf "%s %s %s %s %s" $hritu $din $tariq $mas $son
    fi
}

printf "%s\n" "$(bongabdo)"
