#!/usr/bin/env sh

# Bangla date count starts with the rising of the sun. So date is corrected to change at 6 in the morning with GMT. If date doesn't change accordingly uncomment line 19  and comment 20.



bongabdo() {
    [ -z $en_date ] && read -p "Enter Date (dd-mm-yyyy): " en_date && [ -z $en_date ] && en_date=$(TZ='Europe/London' date +%-d-%-m-%-Y)
#    [ -z $en_date ] && read -p "Enter Date (dd-mm-yyyy): " en_date && [ -z $en_date ] && en_date=$(date +%-d-%-m-%-Y)
    en_dt=$(echo $en_date | tr '-' '\n' | sed -n "1p" | sed "s/^0//")
    en_m=$(echo $en_date | tr '-' '\n' | sed -n "2p" | sed "s/^0//")
    en_y=$(echo $en_date | tr '-' '\n' | sed -n "3p" | sed "s/^0//")

    leap_year=$(( $en_y % 4 ))
    en_week_day=$(date --date=$en_y-$en_m-$en_dt +%u)
    # en_week_day=$(date +%u)

    if [ $en_m -eq 4 ]; then
        if [ $en_dt -le 13 ]; then
        bn_y=$(( $en_y - 594 ))
    else 
        bn_y=$(( $en_y - 593 ))
        fi

    elif [ $en_m -lt 4 ]; then
        bn_y=$(( $en_y - 594 ))
    elif [ $en_m -gt 4 ]; then
        bn_y=$(( $en_y - 593 ))
    fi

    if [ $en_m -eq 4 ]; then
        if [ $en_dt -lt 14 ]; then
            bn_m=c
            bn_s=6
            bn_dt=$(( $en_dt + 14 + 3 ))
        elif [ $en_dt -ge 14 ]; then
            bn_m=1
            bn_s=1
            bn_dt=$(( $en_dt - 14 + 1 ))
        fi
    fi

    if [ $en_m -eq 5 ]; then
        if [ $en_dt -lt 15 ]; then
            bn_m=1
            bn_s=1
            bn_dt=$(( $en_dt + 15 + 2 ))
        elif [ $en_dt -ge 15 ]; then
            bn_m=2
            bn_s=1
            bn_dt=$(( $en_dt - 15 + 1 ))
        fi
    fi

    if [ $en_m -eq 6 ]; then
        if [ $en_dt -lt 15 ]; then
            bn_m=2
            bn_s=1
            bn_dt=$(( $en_dt + 15 + 2 ))
        elif [ $en_dt -ge 15 ]; then
            bn_m=3
            bn_s=2
            bn_dt=$(( $en_dt - 15 + 1 ))
        fi
    fi

    if [ $en_m -eq 7 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=3
            bn_s=2
            bn_dt=$(( $en_dt + 16 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=4
            bn_s=2
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 8 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=4
            bn_s=2
            bn_dt=$(( $en_dt + 16 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=5
            bn_s=3
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 9 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=5
            bn_s=3
            bn_dt=$(( $en_dt + 16 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=6
            bn_s=3
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 10 ]; then
        if [ $en_dt -lt 17 ]; then
            bn_m=6
            bn_s=3
            bn_dt=$(( $en_dt + 15 ))
        elif [ $en_dt -ge 17 ]; then
            bn_m=7
            bn_s=4
            bn_dt=$(( $en_dt - 17 + 1 ))
        fi
    fi

    if [ $en_m -eq 11 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=7
            bn_s=4
            bn_dt=$(( $en_dt + 14 + 1 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=8
            bn_s=4
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 12 ]; then
        if [ $en_dt -lt 16 ]; then
            bn_m=8
            bn_s=4
            bn_dt=$(( $en_dt + 14 + 1 ))
        elif [ $en_dt -ge 16 ]; then
            bn_m=9
            bn_s=5
            bn_dt=$(( $en_dt - 16 + 1 ))
        fi
    fi

    if [ $en_m -eq 1 ]; then
        if [ $en_dt -lt 15 ]; then
            bn_m=9
            bn_s=5
            bn_dt=$(( $en_dt + 13 + 3 ))
        elif [ $en_dt -ge 15 ]; then
            bn_m=m
            bn_s=5
            bn_dt=$(( $en_dt - 15 + 1 ))
        fi
    fi

    if [ $en_m -eq 2 ]; then
        if [ $en_dt -lt 14 ]; then
            bn_m=m
            bn_s=5
            bn_dt=$(( $en_dt + 12 + 5 ))
        elif [ $en_dt -ge 14 ]; then
            bn_m=f
            bn_s=6
            bn_dt=$(( $en_dt - 14 + 1 ))
        fi
    fi

    if [ $en_m -eq 3 ]; then
        if [ $en_dt -lt 15 ]; then
            if [ $leap_year -ne 0 ]; then
                bn_m=f
                bn_s=6
                bn_dt=$(( $en_dt + 15 ))
            else
                bn_m=f
                bn_s=6
                bn_dt=$(( $en_dt + 15 + 1 ))
            fi
        elif [ $en_dt -ge 15 ]; then
            bn_m=c
            bn_s=6
            bn_dt=$(( $en_dt - 15 + 1 ))
        fi
    fi

    if [ -z $txt ]; then
        din=$(printf "%s" $en_week_day | sed 's/1/সোম/;s/2/মঙ্গল/;s/3/বুধ/;s/4/বৃহঃ/;s/5/শুক্র/;s/6/শনি/;s/7/রবি/')
        tariq=$(printf "%s" $bn_dt | sed 's/1/১/g;s/2/২/g;s/3/৩/g;s/4/৪/g;s/5/৫/g;s/6/৬/g;s/7/৭/g;s/8/৮/g;s/9/৯/g;s/0/০/g')
        mas=$(printf "%s" $bn_m | sed 's/1/বৈশাখ/;s/2/জ্যৈষ্ঠ/;s/3/আষাঢ়/;s/4/শ্রাবণ/;s/5/ভাদ্র/;s/6/আশ্বিন/;s/7/কার্তিক/;s/8/অগ্রহায়ণ/;s/9/পৌষ/;s/m/মাঘ/;s/f/ফাল্গুন/;s/c/চৈত্র/')
        son=$(printf "%s" $bn_y | sed 's/1/১/g;s/2/২/g;s/3/৩/g;s/4/৪/g;s/5/৫/g;s/6/৬/g;s/7/৭/g;s/8/৮/g;s/9/৯/g;s/0/০/g')
        hritu=$(printf "%s" $bn_s | sed 's/1/গ্রীষ্ম/;s/2/বর্ষা/;s/3/শরৎ/;s/4/হেমন্ত/;s/5/শীত/;s/6/বসন্ত/')
    else
        din=$(printf "%s" $en_week_day | sed 's/1/Som/;s/2/Mongol/;s/3/Budh/;s/4/Briho/;s/5/Shukro/;s/6/Shoni/;s/7/Robi/')
        tariq=$bn_dt
        mas=$(printf "%s" $bn_m | sed 's/1/Boishakh/;s/2/Jaishtha/;s/3/Aashar/;s/4/Srabon/;s/5/Vhadra/;s/6/Aashwin/;s/7/Kartik/;s/8/Aagrahayon/;s/9/Poush/;s/m/Magh/;s/f/Falgun/;s/c/Chaitra/')
        son=$bn_y
        hritu=$(printf "%s" $bn_s | sed 's/1/Grishsho/;s/2/Borsha/;s/3/Sharot/;s/4/Hemanta/;s/5/Sheet/;s/6/Bosonto/')
    fi

    if [ $dt_f -eq 1 ]; then
         printf "%s %s %s" $din $tariq $mas
    elif [ $dt_f -eq 2 ]; then
        printf "%s %s %s %s" $din $tariq $mas $son
    elif [ $dt_f -eq 3 ]; then
        printf "%s %s %s" $hritu $tariq $mas
    elif [ $dt_f -eq 4 ]; then
        printf "%s %s %s %s" $hritu $tariq $mas $son
    elif [ $dt_f -eq 5 ]; then
        printf "%s %s" "$tariq "$mas
    else
        printf "%s %s %s %s %s" $hritu $din $tariq $mas $son
    fi
}


engabdo() {
    [ -z $bn_date ] && read -p "Enter Bangla Tariq (dd-mm-yyyy): " bn_date
    bn_dt=$(echo $bn_date | tr '-' '\n' | sed -n "1p" | sed "s/^0//")
    bn_m=$(echo $bn_date | tr '-' '\n' | sed -n "2p" | sed "s/^0//")
    bn_y=$(echo $bn_date | tr '-' '\n' | sed -n "3p" | sed "s/^0//")

    if [ $bn_m -lt 9 ]; then
            en_y=$(( $bn_y + 593 ))
            else
            en_y=$(( $bn_y + 593 + 1 ))
    fi
    if [ $bn_m -eq 9 ]; then
        if [ $bn_dt -le 16 ]; then
            en_y=$(( $bn_y + 593 ))
            else
            en_y=$(( $bn_y + 594 ))
         fi
     fi

    if [ $bn_m -gt 9 ]; then
            en_y=$(( $bn_y + 594 ))
    fi

    if [ $bn_m -eq 1 ]; then
        if [ $bn_dt -lt 18 ]; then
            en_m=4
            en_dt=$(( $bn_dt + 13 ))
        elif [ $bn_dt -ge 18 ]; then
            en_m=5
            en_dt=$(( $bn_dt - 17 ))
        fi
    fi

    if [ $bn_m -eq 2 ]; then
        if [ $bn_dt -lt 18 ]; then
            en_m=5
            en_dt=$(( $bn_dt + 14 ))
        elif [ $bn_dt -ge 18 ]; then
            en_m=6
            en_dt=$(( $bn_dt - 17 ))
        fi
    fi

    if [ $bn_m -eq 3 ]; then
        if [ $bn_dt -lt 17 ]; then
            en_m=6
            en_dt=$(( $bn_dt + 14 ))
        elif [ $bn_dt -ge 17 ]; then
            en_m=7
            en_dt=$(( $bn_dt - 16 ))
        fi
    fi

    if [ $bn_m -eq 4 ]; then
        if [ $bn_dt -lt 17 ]; then
            en_m=7
            en_dt=$(( $bn_dt + 15 ))
        elif [ $bn_dt -ge 17 ]; then
            en_m=8
            en_dt=$(( $bn_dt - 16 ))
        fi
    fi

    if [ $bn_m -eq 5 ]; then
        if [ $bn_dt -lt 17 ]; then
            en_m=8
            en_dt=$(( $bn_dt + 15 ))
        elif [ $bn_dt -ge 17 ]; then
            en_m=9
            en_dt=$(( $bn_dt - 16 ))
        fi
    fi

    if [ $bn_m -eq 6 ]; then
        if [ $bn_dt -lt 16 ]; then
            en_m=9
            en_dt=$(( $bn_dt + 15 ))
        elif [ $bn_dt -ge 16 ]; then
            en_m=o
            en_dt=$(( $bn_dt - 15 ))
        fi
    fi

    if [ $bn_m -eq 7 ]; then
        if [ $bn_dt -lt 16 ]; then
            en_m=o
            en_dt=$(( $bn_dt + 16 ))
        elif [ $bn_dt -ge 16 ]; then
            en_m=n
            en_dt=$(( $bn_dt - 15 ))
        fi
    fi

    if [ $bn_m -eq 8 ]; then
        if [ $bn_dt -lt 16 ]; then
            en_m=n
            en_dt=$(( $bn_dt + 15 ))
        elif [ $bn_dt -ge 16 ]; then
            en_m=d
            en_dt=$(( $bn_dt - 15 ))
        fi
    fi

    if [ $bn_m -eq 9 ]; then
        if [ $bn_dt -lt 17 ]; then
            en_m=d
            en_dt=$(( $bn_dt + 15 ))
        elif [ $bn_dt -ge 17 ]; then
            en_m=1
            en_dt=$(( $bn_dt - 16 ))
        fi
    fi
    
    if [ $bn_m -eq 10 ]; then
        if [ $bn_dt -lt 18 ]; then
            en_m=1
            en_dt=$(( $bn_dt + 14 ))
        elif [ $bn_dt -ge 18 ]; then
            en_m=2
            en_dt=$(( $bn_dt - 17 ))
        fi
    fi

    bn_leap_year=$(( $en_y % 4 ))

    if [ $bn_m -eq 11 ]; then
        if [ $bn_leap_year -ne 0 ]; then
            if [ $bn_dt -lt 16 ]; then
            en_m=2
            en_dt=$(( $bn_dt + 13 ))
            elif [ $bn_dt -ge 16 ]; then
            en_m=3
            en_dt=$(( $bn_dt - 15 ))
            fi
        else
            if [ $bn_dt -lt 17 ]; then
            en_m=2
            en_dt=$(( $bn_dt + 13 ))
            elif [ $bn_dt -ge 16 ]; then
            en_m=3
            en_dt=$(( $bn_dt - 16 ))
            fi
        fi
    fi

    if [ $bn_m -eq 12 ]; then
        if [ $bn_dt -lt 18 ]; then
            en_m=3
            en_dt=$(( $bn_dt + 14 ))
        elif [ $bn_dt -ge 18 ]; then
            en_m=4
            en_dt=$(( $bn_dt - 17 ))
        fi
    fi

        en_month_format=$(printf "%s" $en_m | sed 's/o/10/;s/n/11/;s/d/12/')
        bn_week_day=$(date --date=$en_y-$en_month_format-$en_dt +%u)

    if [ -z $txt ]; then
        din=$(printf "%s" $bn_week_day | sed 's/1/সোম/;s/2/মঙ্গল/;s/3/বুধ/;s/4/বৃহঃ/;s/5/শুক্র/;s/6/শনি/;s/7/রবি/')
        tariq=$(printf "%s" $en_dt | sed 's/1/১/g;s/2/২/g;s/3/৩/g;s/4/৪/g;s/5/৫/g;s/6/৬/g;s/7/৭/g;s/8/৮/g;s/9/৯/g;s/0/০/g')
        mas=$(printf "%s" $en_m | sed 's/1/জানুয়ারি/;s/2/ফেব্রুয়ারি/;s/3/মার্চ/;s/4/এপ্রিল/;s/5/মে/;s/6/জুন/;s/7/জুলাই/;s/8/আগস্ট/;s/9/সেপ্টেম্বর/;s/o/অক্টোবর/;s/n/নভেম্বর/;s/d/ডিসেম্বর/')
        son=$(printf "%s" $en_y | sed 's/1/১/g;s/2/২/g;s/3/৩/g;s/4/৪/g;s/5/৫/g;s/6/৬/g;s/7/৭/g;s/8/৮/g;s/9/৯/g;s/0/০/g')
    else
        din=$(printf "%s" $bn_week_day | sed 's/1/Som/;s/2/Mongol/;s/3/Budh/;s/4/Briho/;s/5/Shukro/;s/6/Shoni/;s/7/Robi/')
        tariq=$en_dt
        mas=$(printf "%s" $en_m | sed 's/1/January/;s/2/February/;s/3/March/;s/4/April/;s/5/May/;s/6/June/;s/7/July/;s/8/August/;s/9/September/;s/o/October/;s/n/November/;s/d/December/')
        son=$en_y
    fi
        printf "%s %s %s %s" $din $tariq $mas $son
}



while getopts "e:b:f:th" o; do case "${o}" in
		h) 	printf "BONGABDO\\n -b: Bangal Tariq\\n -e: English Date\\n -t: Display In English Text\\n -f: Date Format\\n -h: Help\\n" && exit 1 ;;
		b) bn_date="${OPTARG}"
		   obdo="${obdo-engabdo}" ;;
		e) en_date="${OPTARG}"
			obdo="${obdo-bongabdo}" ;;
		f) dt_f="${OPTARG}" ;;
		t) txt="0" ;;
esac done

[ -z $dt_f ] && dt_f="0"

obdo="${obdo-bongabdo}"
$obdo
